/* auto-generated by NAPI-RS */
/* eslint-disable */

export type PhaseStatus = "passed" | "sent" | "unconfirmed" | "skipped" | "error";

export type Verdict =
  | "authentication_confirmed"
  | "data_plane_confirmed"
  | "unconfirmed"
  | "local_error";
