/* auto-generated by NAPI-RS */
/* eslint-disable */

export type PhaseStatus = "passed" | "sent" | "unconfirmed" | "skipped" | "error";

export type Verdict =
  | "authentication_confirmed"
  | "data_plane_confirmed"
  | "unconfirmed"
  | "local_error";
export interface PhaseResult {
  phase: string
  target?: string
  status: PhaseStatus
  durationMs: number
  sentBytes: number
  receivedBytes: number
  detail?: string
}

export declare function probeFile(configPath: string, options?: ProbeOptions | undefined | null): Promise<ProbeReport>

export declare function probeKeyFile(privateKeyPath: string, peerKey: string, endpoint: string, options?: ProbeKeyFileOptions | undefined | null): Promise<ProbeReport>

export interface ProbeKeyFileOptions {
  address?: string
  allowedIps?: Array<string>
  ping?: Array<string>
  resolve?: Array<string>
  dnsServer?: string
  handshakeTimeoutMs?: number
  pingTimeoutMs?: number
  dnsTimeoutMs?: number
  deadlineMs?: number
}

export interface ProbeOptions {
  ping?: Array<string>
  resolve?: Array<string>
  dnsServer?: string
  handshakeTimeoutMs?: number
  pingTimeoutMs?: number
  dnsTimeoutMs?: number
  deadlineMs?: number
}

export interface ProbeReport {
  schemaVersion: number
  verdict: Verdict
  endpoint: string
  resolvedEndpoint?: string
  localUdpAddress?: string
  clientPublicKey: string
  durationMs: number
  sentBytes: number
  receivedBytes: number
  phases: Array<PhaseResult>
}

export declare function version(): string
